# -*- coding: utf-8 -*-
"""PYTHON FOR DATA SCIENCE ASSESSMENT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tXWBNqajoZrhhZXQLd69u6Ys4i-VGaPA

To find House price after 7 years using Linear Regression.
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

from google.colab import files
data = files.upload()

df = pd.read_csv('Housing.csv')
df

df.head()

df.tail()

df['MainRoad'] = df.mainroad.map({'no': 0 , 'yes': 1})
df['GuestRoom'] = df.guestroom.map({'no': 0, 'yes': 1})
df['Basement'] = df.basement.map({'no': 0, 'yes': 1})
df['AirConditioning'] = df.airconditioning.map({'no': 0, 'yes': 1})
df['PrefArea'] =df.prefarea.map({'no':0, 'yes':1})
df['FurnishingStatus'] = df.furnishingstatus.map({'unfurnished':0, 'semi-furnished':1,'furnished':2})
df['HotWaterHeating'] = df.hotwaterheating.map({'no': 0 , 'yes': 1})

df.drop(['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea','furnishingstatus'],axis=1,inplace=True)

df.head(10)

df.columns

X=df[[ 'area', 'bedrooms', 'bathrooms', 'stories', 'parking','MainRoad', 'GuestRoom', 'Basement', 'HotWaterHeating','AirConditioning', 'PrefArea', 'FurnishingStatus']]
Y=df['price']

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=50)

from sklearn.linear_model import LinearRegression
lin_model = LinearRegression()
lin_model.fit(X_train,Y_train)

predict = lin_model.predict(X_test)
predict

plt.scatter(Y_test,predict, c = 'green')

from sklearn.metrics import r2_score
r2_score(Y_test, predict)