# -*- coding: utf-8 -*-
"""Labtask_1_UserData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wq_aANET-xpFe0mo-gU7MyAdV2cYl7wh

**INFORMATION OF USER FROM COMPANY DATABASES**
"""

import pandas as pd
from google.colab import files
Data = files.upload()

df = pd.read_csv('User_Data.csv')
df.head()

df.columns

df['gender'] = df.Gender.map({'Male': 1, 'Female': 0})
df.drop(['Gender'],axis = 1, inplace = True)

df.head()

df.columns

X = df[['Age','EstimatedSalary','gender']]
Y = df['Purchased']

"""PAIRPLOT"""

import seaborn as sns
sns.pairplot(df)

print(X[:10])
print('---------------------------------')
print(Y[:10])

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state =0)

from sklearn.preprocessing import StandardScaler
std_scale = StandardScaler()
X_train = std_scale.fit_transform(X_train)
X_test = std_scale.transform(X_test)

print(X_train[:10])

"""LOGISTIC REGRESSION"""

from sklearn.linear_model import LogisticRegression

logmodel = LogisticRegression()
logmodel.fit(X_train,Y_train)

prediction = logmodel.predict(X_test)
prediction

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(prediction,Y_test)
cm

"""**Accuracy**"""

from sklearn.metrics import accuracy_score

print("Accuracy:",accuracy_score(prediction,Y_test))